In [1]:
import numpy as np

#### подготовка строки, подбор размерности трафарета шифр-таблицы

In [2]:
STRING_TO_ENCODE = "НЕБЫВАЛЫЕСКИДКИНАВСЕКРИПТОВАЛЮТЫ"

def prepare_string(string):
    """append additional spaces so `len(string) % 4 == 0`"""
    return string + ' ' *  ((4 - len(string) % 4) % 4)

def get_possible_dims(str_len):
    res= []
    for x in range(1, int(str_len**.5 +1)):
        if (str_len % x == 0 and (str_len // x) % 2 == 0 and x % 2 == 0):
            res.append([x,str_len//x])
    return res

string_to_encode = prepare_string(STRING_TO_ENCODE)
N, M = sorted(get_possible_dims(len(string_to_encode)), key = lambda x: (x[0] - x[1])**2)[0]
print('размерность решетки: [{}, {}]'.format(N, M))

размерность решетки: [4, 8]


#### генерация трафарета шифр-таблицы

In [3]:
def generate_grid(N, M):
    grid_pattern = np.random.randint(4, size = (N // 2, M // 2))

    grid_pattern_1quarter = grid_pattern
    grid_pattern_2quarter = np.fliplr(grid_pattern)
    grid_pattern_3quarter = np.rot90(np.rot90(grid_pattern))
    grid_pattern_4quarter = np.flipud(grid_pattern)

    grid = np.concatenate([grid_pattern_1quarter, grid_pattern_2quarter], axis=1)
    grid = np.concatenate([grid, np.concatenate([grid_pattern_4quarter, grid_pattern_3quarter], axis=1)])
    return grid

pattern = generate_grid(N, M)
print(1*pattern)

[[0 0 2 0 0 2 0 0]
 [0 0 0 2 2 0 0 0]
 [0 0 0 2 2 0 0 0]
 [0 0 2 0 0 2 0 0]]


#### кодирование

In [4]:
def fill_in_the_line_by_pattern(str_to_fiil_in, context, placeholder):
    for i in range(str_to_fiil_in.count(placeholder)):
        str_to_fiil_in = str_to_fiil_in.replace(placeholder, str(context[i]), 1)
    return str_to_fiil_in

def encode(pattern, str_to_encode):
    code_string = "".join(map(str, 1*pattern.ravel()))    
    for i in range(4):
        symbols_to_be_filled = code_string.count(str(i))
        code_string = fill_in_the_line_by_pattern(code_string, str_to_encode, str(i))
        str_to_encode = str_to_encode[symbols_to_be_filled:]
    return code_string

encoded_str = encode(pattern, STRING_TO_ENCODE)
encoded_str

'НЕТБЫОВАЛЫЕВАСКИДКИЛЮНАВСЕТКРЫИП'

#### декодирование

In [5]:
def decode(encoded_str, pattern):
    encoded_str_joined_with_pattern = np.array(list(zip("".join(map(str, pattern.ravel())), encoded_str)))
    return "".join(np.array(sorted(encoded_str_joined_with_pattern, key=lambda x: int(x[0])))[:,1])

decoded_str = decode(encoded_str, pattern)
decoded_str

'НЕБЫВАЛЫЕСКИДКИНАВСЕКРИПТОВАЛЮТЫ'

#### совпадают ли исходная и декодированная строки?

In [6]:
STRING_TO_ENCODE == decoded_str

True